name: "HARelay"
description: "Secure remote access to Home Assistant via HARelay"
version: "1.2.2"
slug: "harelay"
url: "https://harelay.com"

host_network: true
init: false
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

startup: application
homeassistant_api: true
auth_api: true

# Enable web UI panel
ingress: true
ingress_port: 8099
panel_icon: "mdi:home-assistant"
panel_title: "HARelay"

options:
  subdomain: ""
  connection_token: ""
  log_level: "info"

schema:
  subdomain: "str?"
  connection_token: "str?"
  log_level: "list(debug|info|warning|error)"
